doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\User\Data:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Data/Mapping/Orm'
                prefix: 'App\User\Data'
                alias: App\User\Data
            App\User\Permission:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Permission/Mapping/Orm'
                prefix: 'App\User\Permission'
                alias: App\User\Permission

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
