security:
    password_hashers:
        App\User\Data\Model\UserData:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: App\User\Data\Model\UserData
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                success_handler: App\Core\EventSubscriber\Security\LoginSubscriber
            logout:
                path: /logout

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
