framework:
    validation:
        email_validation_mode: html5
        mapping:
            paths: '%validator.mapping.paths%'

when@test:
    framework:
        validation:
            not_compromised_password: false
