services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Core\EventSubscriber\Orm\TimestampSubscriber:
        tags:
            - name: doctrine.event_subscriber
